git add --global user.name 'thiagobrandam'
git add --global user.email 'thiago@redealumni.com'
git add --global github.user 'thiagobrandam'
git add --global color.ui 'auto'
git add --global push.default 'upstream'