git config --global user.name 'Thiago Brandão'
git config --global user.email 'thiago@redealumni.com'
git config --global github.user 'thiagobrandam'
git config --global color.ui 'auto'
git config --global push.default 'upstream'
git config --global merge.conflictstyle 'diff3'